[package]
name = "ad4min"
version = "0.0.4"
description = "Administration of ad4m services"
authors = ["Kaichao Sun"]
license = ""
repository = ""
default-run = "ad4min"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
log4rs = "1.0.0"
nix = "0.23.1"
portpicker = "0.1.1"
libc = "0.2.121"
directories = "4.0.1"
opener = "0.5.0"
open = "2.0.1"
tauri = { version = "1.0.0-rc.7", features = ["api-all", "clipboard", "gtk-tray", "system-tray", "wry"], default-features = false }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol"]

dev = []
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol"]
