name: "release"
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-10.15, ubuntu-18.04, windows-2019]
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.13

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-10.15'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: install app dependencies and info
        run: npm install && npm run tauri info
      - name: download Linux & MacOS ad4m-host
        run: ./scripts/setup-binaries.sh
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-18.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libcanberra-gtk-module libcanberra-gtk3-module build-essential curl wget libssl-dev libgtk-3-dev squashfs-tools libgtksourceview-3.0-dev libappindicator3-dev patchelf librsvg2-dev ayatana-indicator-application
      - name: download Windows ad4m-host
        if: matrix.platform == 'windows-2019'
        run: |
          wget "https://github.com/perspect3vism/ad4m-host/releases/download/v0.0.12/ad4m-windows-x64.exe" -outfile "src-tauri/bins/ad4m-x86_64-pc-windows-gnu.exe"
          wget "https://github.com/perspect3vism/ad4m-host/releases/download/v0.0.12/ad4m-windows-x64.exe" -outfile "src-tauri/bins/ad4m-x86_64-pc-windows-msvc.exe"
      - name: build the app
        run: npm run build-all
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Ad4min v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: true
